### ISSUE TITLE
Есть идея переписать админку MODX EVO с использованием данного решения

### ISSUE THREAD

**Issue by Dmi3yy** [XanderBass/quadbraces#1]
А то там давно проситься навести порядок:) в целом можно использовать и внутреннее АПИ. 
но тогда прийдется его пилить немного под бекенд. Что б выносить все нужное в Файлы. А так тут все уже  готово для того что б собрать то что надо. Даст возможность как кастомизировать все так и наконецто навести там порядок

**Comment by XanderBass** [comment]
Здравия!

Прошу прощения за столь долгий ответ - не всегда на связи здесь.

Эта идея давно уже витает в воздухе. Более того, я даже пытался капитально рефакторить сам базовый класс DocumentParser и переделывать весь MODX в целом. Концепция-то прекрасная за вычетом кучи мусора. Правда забил уже на четвёртой итерации рефакторинга. Скажу так: MODX легче просто переписать. У меня есть вообще более глобальная идея. На основе концепции MODX написать нормальный движок.

Вообще было бы неплохо интегрировать в MODX QuadBraces в качестве основного парсера. В сучности-то один и тот же синтаксис. Собственно можно на основе QuadBraces переписать основной класс, я думаю. Банально наследованием. Правда возни будет - будь здоров.

В общем пишите, подумаем, обсудим =)
